name: Run test

on:
  push:
    branches:
      - master

jobs:
  e2e_tests:
    name: E2e Test For Core package
    # needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run e2e Tests
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        name: "upload artfact"
        if: success() || failure()
        with:
          name: my-artifacts
          path: ./test/scripts/*.out.txt
